name: CI-CD-Pipeline-to-AWS-ElastikBeastalk
env:
  EB_PACKAGE_S3_BUCKET_NAME : "flask-aoplication-packages"
  EB_APPLICATION_NAME       : "MyFlask"
  EB_ENVIROMMENT_NAME       : "MyFlask-env"
  DEPLOY_PACKAGE_NAME       : "flash_app_${{ github.sha }}.zip"
  AWS_REGION_NAME           : "eu-west-3"

on:
  push:
    branches:
      - main
jobs:
  
  my_ci_part:
    runs-on: ubuntu-latest

    
    steps:
      - name: Git clone our repo
        uses: actions/checkout@v3

      
      - name: Create ZIP deployment package
        run: zip -r $ {{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*



