name: CI-CD-Pipeline-to-AWS-ElastikBeastalk
env:
  EB_PACKAGE_S3_BUCKET_NAME : "flask-aoplication-packages"
  EB_APPLICATION_NAME       : "MyFlask"
  EB_ENVIROMMENT_NAME       : "MyFlask-env"
  DEPLOY_PACKAGE_NAME       : "flash_app_${{ github.sha }}.zip"
  AWS_REGION_NAME           : "eu-west-3"

on:
  push:
    branches:
      - main
jobs:
  
  my_ci_part:
    runs-on : ubuntu-latest

    
    steps:
      - name: Git clone our repo
        uses: actions/checkout@v3

      
      - name: Create ZIP deployment package
        run : zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*
        
        
      - name: Configure my AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-acess-key-id     : "AKIAZOWPYAO752TXZTH7"
          aws-secret-access-key: "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"
          aws-region           : ${{ env.AWS_REGION_NAME }}
          
      - name: Copy Deployment package to S3 bucket
        run : aws cp ${{ env.DEPLOY_PACKAGE_NAME }} s3://${{ env.EB_PACKAGE_S3_BUCKET_NAME }}/
        
      - name: Print Happy Message fot CI finish
        run : echo "CI Pipeline part finished successfully!"
          


